wheel:
  type: HOLOGRAM
  height: 25
  width: 25
  # this should NEVER be higher then the amount of colors configured above
  sectors: 12

  hologram:
    icon: '█'

  block:
    schematic: 'path/to/schematic'
    # Possible types: TERRACOTTA, WOOL, STAINED_GLASS, CONCRETE, GLAZED_TERRACOTTA
    type: 'TERRACOTTA'

  runs:
    - max-runs: 40
      default-tick-duration: 10
      runs:
        - first: 1
          last: 20
          tick-duration: 10
        - first: 20
          last: 30
          tick-duration: 15
        - first: 30
          last: 35
          tick-duration: 20
        - first: 35
          last: 37
          tick-duration: 25
        - first: 37
          last: 38
          tick-duration: 30
        - first: 38
          last: 39
          tick-duration: 35
        - first: 39
          last: 40
          tick-duration: 40

sounds:
  tick: 'BLOCK_NOTE_BLOCK_PLING'
  finish: 'ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR'

messages:
  prefix: '&c&lDangerWheel &8» '

  reloaded: '&eConfiguration file and event scripts have been reloaded.'
  not-for-console: '&eThe console cannot execute this command.'

events:
  - name: 'CHANGE_WORLD_DIFFICULTY'
    item:
      # 1.13 and up, for colored class you should for example use YELLOW_STAINED_GLASS, under you should use STAINED_GLASS:4
      material: 'GRASS'
      name: '&eChange world difficulty'
      lore:
        - '&eChanges difficulty of all worlds to'
        - '&bHARD &efor &b30 minutes&e!'
    script: 'changediff.js'