wheel:
  type: HOLOGRAM
  height: 25
  width: 25
  # this should NEVER be higher then the amount of colors configured above
  sectors: 12

  # Amount of seconds until the wheel starts spinning after executing the command.
  delay: 10

  hologram:
    icon: '█'

    header:
      - '&4▇▇▇    '
      - '&4▇    '
      - ''
    footer:
      - ''
      - '&eYou can spin this wheel to possibly get some nice rewards,'
      - '&ebut beware! This wheel can have some &cdangerous tendencies&e!'
      - ''
      - '&b&lLegenda:'
      - '&e█ Changes World Difficulty   &r-   &b█ Nobody knows o_O'

  block:
    # Possible types: TERRACOTTA, WOOL, STAINED_GLASS, CONCRETE, GLAZED_TERRACOTTA
    type: 'TERRACOTTA'

sounds:
  tick: 'BLOCK_NOTE_BLOCK_PLING'
  finish: 'ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR'

messages:
  prefix: '&c&lDangerWheel &8» '

  not-for-console: '&eThe console cannot execute this command.'
  wheel:
    no-wheel: '&eThere is no wheel that can be started! &bPlease contact an administrator for this.'
    starting:
      starting: '&eThe wheel of danger will now start.'
      default: '&e{timer} ...'
      '10': '&eThe wheel of danger will start in &b10 seconds&e.'
      '9': ''
      '8': ''
      '7': ''
      '6': ''
    no-event: '&eThe wheel of danger ended on nothing this time around ...'
    event: '&eThe wheel of danger ended on &b{eventName}&e.'

  admin:
    reloaded: '&eConfiguration file and event scripts have been reloaded.'
    location-set: '&eThe danger wheel location has been set!'
    error: '&cAn error occured, please &4check the console &cfor more info!'

# Every color that does not have an event bound to it will have a random event from this list.
events:
  - name: 'Change World Difficulty'
    script: 'changediff.js'
    # List of available colors can be found at:
    # https://git.dbsoftwares.eu/dbsoftwares/dangerwheel/blob/master/src/main/java/com/dbsoftwares/dangerwheel/utils/objects/CircleColor.java
    color: 'YELLOW'